### ISSUE TITLE
Capabilities Interoperabiliteit uitwerken

### ISSUE THREAD

**Issue by marcvanandel** [ibds-fds/architectuur#3]
Van het capability model moet hoofdstuk Interoperabiliteit uitgewerkt worden.

**Comment by gjaaf** [comment]
Voor volgende week woensdag moeten we hier doorheen gegaan zijn.

**Comment by marcvanandel** [comment]
Opruimen. Beheer en sturing op issues gebeurt ergens anders (nog niet helemaal duidelijk en ... nog gesloten)
