### ISSUE TITLE
Capabilities Data met waarde uitwerken

### ISSUE THREAD

**Issue by marcvanandel** [ibds-fds/architectuur#4]
Van het capability model dient de Data met waarde uitgewerkt te worden.

**Comment by gjaaf** [comment]
Voor volgende week woensdag moeten we hier door gegaan zijn.

**Comment by marcvanandel** [comment]
Opruimen. Beheer en sturing op issues gebeurt ergens anders (nog niet helemaal duidelijk en ... nog gesloten)
