### ISSUE TITLE
Oplossingsconcept uitwerken obv federatief en events

### ISSUE THREAD

**Issue by marcvanandel** [ibds-fds/architectuur#6]
Op basis van het basisconcept, de capabilities en principes die langzaam naar boven borrelen, dient er een oplossingsrichting geschetst te gaan worden. D'r zijn daar wel ideeën voor ... maar een uitwerking hiervan en ook mogelijke concrete beproevingen moeten nog gemaakt worden.

Onderdelen die er in ieder geval in moeten zitten:

- [ ] federatief; like DNS
- [ ] events; afgekeken van Event Sourcing

**Comment by marcvanandel** [comment]
Inspiratie:
- [SensRNet Architecture](https://kadaster-labs.github.io/sensrnet-home/Architecture/)
- [NLX](https://nlx.io/) (met achterliggende standaard [FSC](https://gitlab.com/commonground/standards/fsc))

**Comment by marcvanandel** [comment]
Besproken met Mike en een eerste akkoord om verder onderzoek te doen

**Comment by marcvanandel** [comment]
Tip van André: Social harvesting. _Anderen_ dan de officiële bronhouder kunnen een bron 'aanmelden' cq 'verklikken' ... waarmee deze al wél bekend kan worden in de / een catalogus.

Voorbeeld: [data.world](https://data.world)

Interessant concept ... 🤔

**Comment by gjaaf** [comment]
Ik denk dat we even een routeplanning hiervoor moeten uitdenken en opschrijven. Dit topic is iets te ruim om ons te  sturen.

**Comment by marcvanandel** [comment]
Opruimen. Beheer en sturing op issues gebeurt ergens anders (nog niet helemaal duidelijk en ... nog gesloten)
